### ISSUE TITLE
[CLI] Diagrama de clases y componentes del CLI.

### ISSUE THREAD

**Issue by baquiax** [baquiax/Compiler#1]
Lo primero que debemos realizar es: diseñar como se estructurará nuestro CLI, en cuanto a clases, paquetes, métodos e interoperabilidad. 
Es decir, indicar que clases o que métodos de clases usaremos y tendremos que crear.
Lo importante de acá es aclarar la funcionalidad de todos los componentes del CLI; aunque estos no sean exactos y super específicos.

@marroq El día de hoy iniciaré el diseño de componentes, y en base a eso nos repartiremos el trabajo.

Los requerimientos se encuentran en: _http://diegofigueroa.github.io/ug-cc4-projects/projects/cli.html_

**La idea es concluir este diseño.**
https://repository.genmymodel.com/baquiax/compiler-cli-design

![image](https://cloud.githubusercontent.com/assets/1281019/3638190/e223a0ca-1039-11e4-80fc-f1d8f1b932ba.png)

**Comment by marroq** [comment]
Anotado, antes de empezar con el código debemos acordar como vamos a tener el diseño del programa, que contendrá cada clase y los archivos .defac en los que estaremos guardando la información en el proceso de compilación

**Comment by baquiax** [comment]
Depués de analizar  la _ESTRUCTURA BÁSICA_ del compilador hemos llegado a este diseño.

Podemos dar como cerrada esta tarea, sujeta a algunos cambios. 
A espera de comentarios de @marroq, tenemos hasta hoy 19 de Julio 20 hrs, para hacer cambios antes de empezar a codear.

Después de las 20 hrs, se subirá el commit con este código.

**Comment by baquiax** [comment]
@marroq  He notado que he tenido un error al generar el código de las clases.
Aparentemente todas estan en un paquete root llamado **cc4**, cosa que no debería ser ya que nuestro CLASSPATH apunta a esa carpeta, y por lo tanto el package root deberia ser **compiler**.

Por favor corregir esto.

**Comment by marroq** [comment]
Ya estamos con la corrección de paquetes lista @baquiax

**Comment by baquiax** [comment]
Gracias @marroq !
El commit fue 3a55335d953074eef392e4de69364079970120bc

Tarea concluida y cerrada.
