### ISSUE TITLE
Modificar el diagrama de clases del diseño.

### ISSUE THREAD

**Issue by baquiax** [baquiax/Compiler#11]
@marroq 

Me parece que como te corresponde la tarea #6, esta tarea te podría servir de ayuda, y aparte actualizaríamos el diagrama.

Saludos

**Comment by marroq** [comment]
Se puede acceder al nuevo diseño en la siguiente dirección
https://repository.genmymodel.com/baquiax/compiler-cli-design/Compiler/_r3V5ENqBEDGyLdMX9tXFiA
