### ISSUE TITLE
Gramática Decaf

### ISSUE THREAD

**Issue by marroq** [baquiax/Compiler#13]
Esta tarea tiene el deber de llevar el desarrollo de la gramática que debemos implementar para el lenguaje Decaf.

**Comment by marroq** [comment]
@baquiax si tenemos mejoras para el lexerDecaf.g deberíamos dejarlo en la Tarea#12 y lo que avancemos en parserDecaf.g colocarlo en esta Tarea.

**Comment by baquiax** [comment]
@marroq  de acuerdo. En la tarea #12 solo necesito que revises que los tokens se reconozcan bien para cerrarlos. tomar en cuenta el nombre de los archivos de las .g

**Comment by marroq** [comment]
@baquiax  está bien, en este momento estoy haciendo cambios en el ParserDecaf sobre los cambios que tiene LexerDecaf
