### ISSUE TITLE
[Development] Compiler structure.

### ISSUE THREAD

**Issue by baquiax** [baquiax/Compiler#3]
La tarea #1 generó dos tareas. La primera #2 ha sido me ha sido asignada. 

Esta tarea corresponderá a @marroq :)

La idea es trabajar en el resto de de clases que conforman el compilador. En ella se deben realizar:
- Imprimir texto descriptivo, simulando que los métodos están completamente implementados.
- Utilizar la clase Compiler.java para verificar si determinada fase tiene habilitada el debugging. `Compiler.debugStages`
- Comentar los métodos de forma bonita :smile: 
- Agregar por último los resultados al Wiki

**Comment by marroq** [comment]
Tarea revisada, ya estoy empezando con el desarrollo de estas clases.
