### ISSUE TITLE
[Nuevas clases] Crear clase en lib/Configuration.java

### ISSUE THREAD

**Issue by baquiax** [baquiax/Compiler#8]
Delegar la tarea de contener la configuración del Compilador, removiendo esto de la clase Scanner.java.

Por ahora sabremos que en esta clase estarán las propiedades estáticas publicas: `HastTable<String, String> flags` e `int stopStage`.

Puede que en un futuro se extienda esta clase, pero para la la primera versión del Compilador solo será esto.

**Comment by marroq** [comment]
@baquiax creé ésta clase ya que la necesito para guiarme en las modificaciones de las instancias que necesitamos corregir en el CLI, perdón por haber tomado tu tarea pero me fue necesario.

**Comment by baquiax** [comment]
:+1:
