### ISSUE TITLE
[Improvement] Dar el control del Compilador a Compiler.java

### ISSUE THREAD

**Issue by baquiax** [baquiax/Compiler#9]
Dar el control completo al compilador. Iniciar proceso de Compilación desde acá.

Acá se elegirá la case a instancias y el parámetro que necesita.

e.g
El proceso requerido llega al `semantic`,  Entonces se debe crear primero un `Ast`, que reciba un `CC4Parser` y que ese parser reciba un `Scanner`. Esta lógica la debe manejar el `Compiler.java`.

**Esta tarea depende directamente de  #8.**

**_@marroq  Debes esperar hasta que la tarea #8 este cerrada para poder inciar esta**_

**Comment by marroq** [comment]
@baquiax 
Podemos dar por finalizada las correcciones al CLI
